#!/usr/bin/perl
use strict;
use warnings;

use Getopt::Long;
use YAML 'LoadFile';
use Text::ParseWords;

GetOptions(
    'o=s' => \my $outname,
    'v'   => \my $verbose,
    'resolution=s'   => \my $resolution,
);

my ($movie) = grep !/\.yml/i, @ARGV;
my ($config) = grep /\.yml/i, @ARGV;

my ($width,$height) = $resolution =~ /(\d+)/g;

if( $config ) {
    $config = LoadFile( $config );
};

my $ffmpeg = $ENV{FFMPEG} || 'ffmpeg';
my @ffmpeg_options = shellwords( $ENV{FFMPEG_OPT});

my @cmd = ("-i" => $movie );

@cmd = ( $ffmpeg => @ffmpeg_options,
         @cmd, '-c:a', 'copy', '-vf', "scale=$width:$height", $outname, '-y' );
warn "@cmd" if $verbose;
system(@cmd) == 0
    or die "$? / $!";
