#!/usr/bin/perl
use strict;
use warnings;

use Getopt::Long;
use Cwd;

GetOptions(
    'o=s' => \my $outname,
    'v'   => \my $verbose,
    'x=s' => \my $x,
    'y=s' => \my $y,
    'framerate=s' => \my $framerate,
);
my ($background) = grep !/\.(mp4|mkv)/i, @ARGV;
my ($video) = grep /\.(mp4|mkv)/i, @ARGV;

my $ffmpeg = 'ffmpeg';

my @cmd = ( $ffmpeg => 
             '-loop', '1',
             '-framerate', $framerate,
             '-i', $background,
             '-i', $video,
             '-filter_complex', "[1][0]overlay=$x:$y:shortest=1[out]",
             '-map', '[out]',
             '-map', '1:a', '-c:a', 'copy',
             '-framerate', $framerate,
             $outname, '-y' );
warn "@cmd" if $verbose;
system(@cmd) == 0
    or die "$? / $!";
