#!/usr/bin/perl
use strict;
use warnings;
use 5.012;

use Getopt::Long;
use YAML 'LoadFile';
use File::Basename;
use lib 'lib';

GetOptions(
    'o=s' => \my $outname,
    'config|c=s' => \my $config,
    'template=s' => \my $template,
    'v'   => \my $verbose,
);

my %escape = (
    '<' => '&lt;',
    '>' => '&gt;',
    '&' => '&amp;',
);

sub xml_escape {
    return $_[0] =~ s!([<>&])!$escape{ $1 }!gre
}

my $cfg = LoadFile( $config );

open my $fh, '<:utf8', $template
    or die "Couldn't read '$template': $!";
open my $out_fh, '>:utf8', $outname
    or die "Couldn't write '$outname': $!";

while( my $line = <$fh>) {
    $line =~ s!\[%\s*(\w+)\s*%\]!xml_escape($cfg->{metadata}->{$1} // "$1")!ge;
    print $out_fh $line;
};

close $out_fh;

# Now use Inkscape (mwahahahha) to center the title and artist
#

#     text-container
my @elements = (qw(
    text-container
    text-title
    text-artist
));

my $elements = join ",",@elements;
my @commands = (
    "select-by-id:$elements",
    'select-list',
    'object-align:hcenter first',
    'export-do',
);

my @cmd =( inkscape => $outname, "--batch-process", "--export-overwrite", "--actions=". join ";", @commands );
warn "[@cmd]";
system(@cmd);
#system(inkscape => $outname, "--batch-process", "--with-gui", "--verb",join( ';', @commands ));
#system(inkscape => $outname, "--batch-process", "--with-gui", "--verb",join( ';', @commands ));
